name: Build
on:
  pull_request:
    paths:
      - 'src/**'
      - '*.{json|js|ts}'
      - '.github/workflows/build.yml'

  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
      - run: |
          PUBLIC_URL=/crytpogram npm run build

      - name: Deploy to branch
        # if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: dist
